# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: aquasecScanner@4
  inputs:
    image: 'alpine:latest'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'registry.aquasec.com/scanner:6.2'
    runOptions: '-v /var/run/containerd.sock:/var/run/containerd.sock -v /tmp:/tmp -e BUILD_JOB_NAME=alpine -e SCALOCK_LOG_LEVEL=DEBUG'
    connection: 'aqua-scanner'
    customFlags: '--direct-cc'
    caCertificates: true